=== Experiment-Creation-Toolkit/experiment-creation-toolkit/resources/schemas/experiment-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "required": [
        "title",
        "authors",
        "tasks"
    ],
    "additionalProperties": false,
    "properties": {
        "$schema": {
            "type": "string",
            "format": "uri-reference"
        },
        "title": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "authors": {
            "type": "array",
            "items": {
                "$ref": "./author-schema.json"
            }
        },
        "tasks": {
            "type": "array",
            "items": {
                "$ref": "./task-schema.json"
            }
        }
    }
}

=== Experiment-Creation-Toolkit/experiment-creation-toolkit/public/data/experiments/UncertaintyViz/config.json
{
    "$schema": "../../../../schemas/experiment-schema.json",
    "title": "Map visualizations for uncertainty in climate projections: a questionnaire",
    "description": "This is an example experiment.",
    "authors": [
        {
            "firstName": "Merel",
            "lastName": "Vogel",
            "email": "m.vogel@52north.de"
        },
        {
            "firstName": "Max",
            "lastName": "Gadomski",
            "email": "max.gadomski@uni-muenster.de"
        }
    ],
    "tasks": [
        {
            "title": "Introduction",
            "widgets": [
                {
                    "type": "text",
                    "properties": {
                        "text": "This questionnaire is part of my master's thesis for the programme Geoinformatics and Spatial Data Science at the University of Münster (DE). It was written in collaboration with 52° North GmbH and is a contribution to the I-CISK project."
                    }
                },
                {
                    "type": "text",
                    "properties": {
                        "text": "The goal of this questionnaire is to find out which type of map is the most suitable for understanding the uncertainty inherent to these forecasts. We highly value your input in shaping effective climate communication!"
                    }
                },
                {
                    "type": "text",
                    "properties": {
                        "heading": "Privacy and data protection statement",
                        "text": "The data collected in this questionnaire will include your responses to the questions presented. The information collected is intended solely for the purpose of research and analysis. It will not be used for any commercial, marketing, or promotional activities. We will not collect or store any personally identifiable information (PII) such as names, email addresses, or other identifying details. Your responses will remain anonymous."
                    }
                },
                {
                    "type": "text",
                    "properties": {
                        "heading": "Consent",
                        "text": "Participation in this questionnaire is entirely voluntary. You are not required to provide any information if you do not wish to do so. By proceeding with this questionnaire, you consent to the collection and use of your responses as described in the privacy statement."
                    }
                },
                {
                    "type": "text",
                    "properties": {
                        "heading": "Contact",
                        "text": "If you have any questions about the questionnaire or concerns about the privacy of your data, please contact me (Merel) at the following email address: m.vogel@52north.org."
                    }
                }
            ]
        },
        {
            "title": "Introductory Questions",
            "widgets": [
                {
                    "type": "input",
                    "properties": {
                        "question": "How often do you use digital maps?",
                        "type": "likert",
                        "properties": {
                            "options": [
                                "Never",
                                "Once a month or less",
                                "Several times a month",
                                "Several times a week",
                                "Daily"
                            ]
                        }
                    }
                },
                {
                    "type": "input",
                    "properties": {
                        "question": "Have you heard of or seen uncertainty information in climate forecasts before this survey?",
                        "type": "likert",
                        "properties": {
                            "options": [
                                "I have never heard of it.",
                                "I have heard of uncertainty information, but not seen it in forecasts",
                                "I have heard of it, but do not understand it",
                                "I understand it to some extent",
                                "I am very familiar with uncertainty information in climate forecasts"
                            ]
                        }
                    }
                }
            ]
        },
        {
            "title": "First Map Prototype",
            "widgets": [
                {
                    "type": "text",
                    "properties": {
                        "text": "Please use the map below to answer the following questions."
                    }
                },
                {
                    "type": "map",
                    "properties": {
                        "title": "USA: National Obesity Rate By State 2015 (3 classes, equal interval)",
                        "data": "LakeCounty_Health_NationalObesityByState_2015.json",
                        "variable": {
                            "id": "Obesity",
                            "unit": "%"
                        },
                        "classificationMethod": "equal interval",
                        "colorScheme": "https://colorbrewer2.org/?type=sequential&scheme=OrRd&n=3"
                    }
                }
            ]
        },
        {
            "title": "Comparison of Two Map Prototypes",
            "widgets": [
                {
                    "type": "text",
                    "properties": {
                        "text": "Please use the two maps below to answer the following questions."
                    }
                },
                {
                    "type": "map",
                    "properties": {
                        "title": "USA: National Obesity Rate By State 2015 (5 classes, equal interval)",
                        "data": "LakeCounty_Health_NationalObesityByState_2015.json",
                        "variable": {
                            "id": "Obesity",
                            "unit": "%"
                        },
                        "classificationMethod": "equal interval",
                        "colorScheme": "https://colorbrewer2.org/?type=sequential&scheme=OrRd&n=5"
                    }
                },
                {
                    "type": "map",
                    "properties": {
                        "title": "USA: National Obesity Rate By State 2015 (5 classes, jenks)",
                        "data": "LakeCounty_Health_NationalObesityByState_2015.json",
                        "variable": {
                            "id": "Obesity",
                            "unit": "%"
                        },
                        "classificationMethod": "jenks",
                        "colorScheme": "https://colorbrewer2.org/?type=sequential&scheme=OrRd&n=5"
                    }
                }
            ]
        }
    ]
}
